name: TP4 - SecWeb - Daily Security Pipeline

permissions:
  security-events: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  dependencies-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google/osv-scanner-action/osv-scanner-action@8dded7155905cd666190a12dc9997000e58d163d
        with:
          scan-args: "--output=osv.sarif --format=sarif ./app"
        continue-on-error: true

      - uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387
        with:
          sarif_file: osv.sarif

  source-code-analysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4

      - run: semgrep scan --config p/java --sarif --output=semgrep.sarif
        continue-on-error: true

      - uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387
        with:
          sarif_file: semgrep.sarif
