name: TP4 - SecWeb  - Security Check on Pull Request

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependencies-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with :
            fetch-depth: 0

      - uses: google/osv-scanner-action/osv-scanner-action@8dded7155905cd666190a12dc9997000e58d163d
        with:
          scan-args: "--output=osv.diff.sarif --format=sarif ./app"
        continue-on-error: true

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: osv-diff-report
          path: osv.diff.sarif

  source-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep differential analysis
        run: |
          semgrep scan \
            --error \
            --baseline-commit ${{ github.event.pull_request.base.sha }} \
            --config "p/java" \
            --sarif \
            --output=semgrep.diff.sarif