name: TP4 - SecWeb - Daily Security Pipeline

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  dependencies-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google/osv-scanner-action@v1
        with:
          scan-directory: ./app
          format: sarif
          output-file: osv.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv.sarif

  source-code-analysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/java
          generateSarif: true
          output: semgrep.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
